name: release binaries

on:
  push:
    tags:
      - v*

env:
  ZIG_URL: https://zigmirror.com/zig-x86_64-linux-0.15.2.tar.xz # TODO
  ZIG_DIR: /opt/zig/0.15.2
  ZIG_VERSION: 0.15.2
  FORGEJO_HOST: https://git.hearth.land

jobs:
  build:
    runs-on: docker
    steps:
      - name: login to forgejo
        run: fj -H ${{ env.FORGEJO_HOST }} auth add-key dragsbruh ${{ secrets.FORGEJO_TOKEN }}

      - name: cache zig
        id: cache-zig
        uses: actions/cache@v4
        with:
          path: ${{ env.ZIG_DIR }}
          key: zig-${{ env.ZIG_VERSION }}-${{ runner.os }}

      - name: download zig
        shell: bash
        if: steps.cache-zig.outputs.cache-hit != 'true'
        run: |
          wget -q ${{ env.ZIG_URL }}
          tar -xJf zig-x86_64-linux-0.15.2.tar.xz
          mkdir -p ${{ env.ZIG_DIR }}
          mv zig-x86_64-linux-0.15.2/* ${{ env.ZIG_DIR }}

      - run: ln -s ${{ env.ZIG_DIR }}/zig /usr/bin/zig

      - uses: actions/checkout@v3

      - name: cross compile
        run: zig build cross -Doptimize=ReleaseSafe

      - name: create release artifacts and changelog
        run: bash .forgejo/workflows/release.sh
        env:
          OUT_DIR: _release/assets/
          CHANGELOG: _release/CHANGELOG.md
          REFNAME: ${{ forgejo.ref_name }}

      - name: upload artifacts
        shell: bash
        run: |
          assets_dir="_release/assets/"
          attachments=()
          for f in "$assets_dir"/*; do
            attachments+=("-a" "$f")
          done

          fj -H ${{ env.FORGEJO_HOST }} release --repo ${{ forgejo.repository }} create \
            -b "$(cat _release/CHANGELOG.md)" \
            "${attachments[@]}" \
            -t ${{ forgejo.ref_name }} \
            "lexyc ${{ forgejo.ref_name }}"
